
// Management Employees
var managementEmployees = [
  {
    'name': 'Mohamed Wagdi Mohamed',
    'id': '1',
    'image': 'https://avatars.githubusercontent.com/u/49213714?v=4',
    'email': 'mohamed@gmail.com',
    'phone': 0540814455,
    'job_title': 'Data Entry',
    'address': 'Faysaliah - Jeddah - Saudi Arabia',
    'department': 'Management',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '5000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'From 8 AM to 4 PM',
    'total_hours': '210',
    'overtime': '20',
    'deduction': '6',
    'bonus': '0',
  },
  {
    'name': 'Heba ALGamala',
    'id': '2',
    'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCbmSfemii3dps00qLZfnVBoxNLD5Q8VRCnK7DYJe8D7iN73s_Gz5KAt4mza-LCemniDs&usqp=CAU',
    'email': 'heba@gmail.com',
    'phone': 05433322223,
    'job_title': 'Software Engineering',
    'address': 'RAbwah - Jeddah - Saudi Arabia',
    'department': 'Management',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '5000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '200',
    'overtime': '30',
    'deduction': '1',
    'bonus': '0',
  },
  {
    'name': 'Doaa Alam',
    'id': '3',
    'image': 'https://cdn.pixabay.com/photo/2016/09/15/17/14/love-1672154_960_720.jpg',
    'email': 'Doaa@gmail.com',
    'phone': 036669996,
    'job_title': 'HR',
    'address': 'Ubhor - Jeddah - Saudi Arabia',
    'department': 'Management',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '5700',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '180',
    'overtime': '10',
    'deduction': '0',
    'bonus': '0',
  },
  {
    'name': 'Raghda',
    'id': '4',
    'image': 'https://previews.123rf.com/images/tommyandone/tommyandone1802/tommyandone180200002/95980754-female-photographer-taking-pictures-outdoors-with-an-old-vintage-camera.jpg',
    'email': 'RAghda@gmail.com',
    'phone': 065326532256,
    'job_title': 'Secrete',
    'address': 'Salamah - Jeddah - Saudi Arabia',
    'department': 'Management',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '4000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '100',
    'overtime': '0',
    'deduction': '6',
    'bonus': '0',
  },

];

// Engineering Employees
var engineeringEmployees = [
  {
    'name': 'Abdullah Bahabib',
    'id': '5',
    'image': 'https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?q=80&w=1965&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'email': 'bahabib@gmail.com',
    'phone': 06352663369,
    'job_title': 'Project Manager',
    'address': 'Sharafyah - Jeddah - Saudi Arabia',
    'department': 'Engineering',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '7000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '80',
    'overtime': '0',
    'deduction': '0',
    'bonus': '0',
  },
  {
    'name': 'Yousef',
    'id': '6',
    'image': 'https://images.pexels.com/photos/925263/pexels-photo-925263.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    'email': 'yousef@gmail.com',
    'phone': 03652144,
    'job_title': 'Site Engineer',
    'address': 'Bawadi - Jeddah - Saudi Arabia',
    'department': 'Engineering',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '8000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '230',
    'overtime': '30',
    'deduction': '4',
    'bonus': '0',
  },
  {
    'name': 'Mahmoud',
    'id': '7',
    'image': 'https://avatars.githubusercontent.com/u/49213714?v=4',
    'email': 'mohamed@gmail.com',
    'phone': 063259852,
    'job_title': 'Site Engineer',
    'address': 'Faysaliah - Jeddah - Saudi Arabia',
    'department': 'Engineering',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '6000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '150',
    'overtime': '10',
    'deduction': '2',
    'bonus': '0',
  },
  {
    'name': 'Mazor',
    'id': '8',
    'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEoBrCTR5XmHc3_kIgpNmpbSiIxVPYFS_1cvdah3XiJ0gZ6ooZc1Q14-dp2f89Loe6mmE&usqp=CAU',
    'email': 'Mazor@gmail.com',
    'phone': 0540814455,
    'job_title': 'Site Engineer',
    'address': 'Zahra - Jeddah - Saudi Arabia',
    'department': 'Engineering',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '4000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '60',
    'overtime': '0',
    'deduction': '0',
    'bonus': '0',
  },
  {
    'name': 'Mohamed Yousef',
    'id': '9',
    'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEoBrCTR5XmHc3_kIgpNmpbSiIxVPYFS_1cvdah3XiJ0gZ6ooZc1Q14-dp2f89Loe6mmE&usqp=CAU',
    'email': 'mohamedyousef@gmail.com',
    'phone': 0540814455,
    'job_title': 'Site Engineer',
    'address': 'Zahra - Jeddah - Saudi Arabia',
    'department': 'Engineering',
    'nationality': 'Paki',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '4000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '60',
    'overtime': '0',
    'deduction': '0',
    'bonus': '0',
  },
];

// Designing Employees
var designingEmployees = [
  {
    'name': 'Sofia',
    'id': '10',
    'image': 'https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w600/2023/10/free-images.jpg',
    'email': 'Sofi@gmail.com',
    'phone': 056325666,
    'job_title': 'Designer',
    'address': 'Ubhor - Jeddah - Saudi Arabia',
    'department': 'Designing',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '10000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '60',
    'overtime': '3',
    'deduction': '0',
    'bonus': '0',
  },
  {
    'name': 'Hossam',
    'id': '11',
    'image': 'https://images.pexels.com/photos/925263/pexels-photo-925263.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    'email': 'hossam@gmail.com',
    'phone': 03652144,
    'job_title': 'Design Engineer',
    'address': 'Bawadi - Jeddah - Saudi Arabia',
    'department': 'Engineering',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '8000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '230',
    'overtime': '30',
    'deduction': '4',
    'bonus': '0',
  },
  {
    'name': 'Joey',
    'id': '12',
    'image': 'https://avatars.githubusercontent.com/u/49213714?v=4',
    'email': 'joey@gmail.com',
    'phone': 063259852,
    'job_title': 'Design Engineer',
    'address': 'Faysaliah - Jeddah - Saudi Arabia',
    'department': 'Engineering',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '6000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '150',
    'overtime': '10',
    'deduction': '2',
    'bonus': '0',
  },
];

// Supervisors Employees
var supervisorsEmployees = [
  {
    'name': 'Mahmoud Ashraf',
    'id': '13',
    'image': 'https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?q=80&w=1965&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'email': 'mahmoudashraf@gmail.com',
    'phone': 06352663369,
    'job_title': 'Supervisor',
    'address': 'Sharafyah - Jeddah - Saudi Arabia',
    'department': 'Supervisor',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '7000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '80',
    'overtime': '0',
    'deduction': '0',
    'bonus': '0',
  },
  {
    'name': 'Amro AbdulAziz',
    'id': '14',
    'image': 'https://images.pexels.com/photos/925263/pexels-photo-925263.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    'email': 'amro@gmail.com',
    'phone': 03652144,
    'job_title': 'Supervisor',
    'address': 'Bawadi - Jeddah - Saudi Arabia',
    'department': 'Supervisor',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '8000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '230',
    'overtime': '30',
    'deduction': '4',
    'bonus': '0',
  },
  {
    'name': 'Reda Nadi',
    'id': '15',
    'image': 'https://avatars.githubusercontent.com/u/49213714?v=4',
    'email': 'reda@gmail.com',
    'phone': 063259852,
    'job_title': 'Supervisor',
    'address': 'Faysaliah - Jeddah - Saudi Arabia',
    'department': 'Supervisor',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '6000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '150',
    'overtime': '10',
    'deduction': '2',
    'bonus': '0',
  },
  {
    'name': 'Mohamed Adel',
    'id': '16',
    'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEoBrCTR5XmHc3_kIgpNmpbSiIxVPYFS_1cvdah3XiJ0gZ6ooZc1Q14-dp2f89Loe6mmE&usqp=CAU',
    'email': 'mohamedadel@gmail.com',
    'phone': 0540814455,
    'job_title': 'Supervisor',
    'address': 'Zahra - Jeddah - Saudi Arabia',
    'department': 'Supervisor',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '4000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '60',
    'overtime': '0',
    'deduction': '0',
    'bonus': '0',
  },
  {
    'name': 'AbdulKareem Kasadi',
    'id': '17',
    'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEoBrCTR5XmHc3_kIgpNmpbSiIxVPYFS_1cvdah3XiJ0gZ6ooZc1Q14-dp2f89Loe6mmE&usqp=CAU',
    'email': 'abdulKareemkasadi@gmail.com',
    'phone': 0540814455,
    'job_title': 'Supervisor',
    'address': 'Zahra - Jeddah - Saudi Arabia',
    'department': 'Supervisor',
    'nationality': 'Yamen',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '4000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '60',
    'overtime': '0',
    'deduction': '0',
    'bonus': '0',
  },
  {
    'name': 'Abo Abdullah',
    'id': '18',
    'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEoBrCTR5XmHc3_kIgpNmpbSiIxVPYFS_1cvdah3XiJ0gZ6ooZc1Q14-dp2f89Loe6mmE&usqp=CAU',
    'email': 'aboabdullah@gmail.com',
    'phone': 0540814455,
    'job_title': 'Supervisor',
    'address': 'Zahra - Jeddah - Saudi Arabia',
    'department': 'Supervisor',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '4000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '60',
    'overtime': '0',
    'deduction': '0',
    'bonus': '0',
  },
  {
    'name': 'Salem Ahmed',
    'id': '19',
    'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEoBrCTR5XmHc3_kIgpNmpbSiIxVPYFS_1cvdah3XiJ0gZ6ooZc1Q14-dp2f89Loe6mmE&usqp=CAU',
    'email': 'salemahmed@gmail.com',
    'phone': 0540814455,
    'job_title': 'Supervisor',
    'address': 'Zahra - Jeddah - Saudi Arabia',
    'department': 'Supervisor',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '4000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5 Days',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'from 8 AM to 4 PM',
    'total_hours': '60',
    'overtime': '0',
    'deduction': '0',
    'bonus': '0',
  },
];

// Labours Employees
var laboursEmployees = [
  {
    'name': 'Mohamed Ali',
    'id': '20',
    'image': 'https://avatars.githubusercontent.com/u/49213714?v=4',
    'email': 'mohamedali@gmail.com',
    'phone': 0540814455,
    'job_title': 'Labours',
    'address': 'Faysaliah - Jeddah - Saudi Arabia',
    'department': 'Labours',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '5000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'From 8 AM to 4 PM',
    'total_hours': '210',
    'overtime': '20',
    'deduction': '6',
    'bonus': '0',
  },
  {
    'name': 'Ahmed AlOla',
    'id': '21',
    'image': 'https://avatars.githubusercontent.com/u/49213714?v=4',
    'email': 'ahmedola@gmail.com',
    'phone': 0540814455,
    'job_title': 'Labours',
    'address': 'Faysaliah - Jeddah - Saudi Arabia',
    'department': 'Labours',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '5000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'From 8 AM to 4 PM',
    'total_hours': '210',
    'overtime': '20',
    'deduction': '6',
    'bonus': '0',
  },
  {
    'name': 'Ahmed Ead',
    'id': '22',
    'image': 'https://avatars.githubusercontent.com/u/49213714?v=4',
    'email': 'ahmedead@gmail.com',
    'phone': 0540814455,
    'job_title': 'Labours',
    'address': 'Faysaliah - Jeddah - Saudi Arabia',
    'department': 'Labours',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '5000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'From 8 AM to 4 PM',
    'total_hours': '210',
    'overtime': '20',
    'deduction': '6',
    'bonus': '0',
  },
  {
    'name': 'AbdulNabi Kamal',
    'id': '23',
    'image': 'https://avatars.githubusercontent.com/u/49213714?v=4',
    'email': 'abulnabikamal@gmail.com',
    'phone': 0540814455,
    'job_title': 'Labours',
    'address': 'Faysaliah - Jeddah - Saudi Arabia',
    'department': 'Labours',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '5000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'From 8 AM to 4 PM',
    'total_hours': '210',
    'overtime': '20',
    'deduction': '6',
    'bonus': '0',
  },
  {
    'name': 'Mohamed ElShawadfi',
    'id': '24',
    'image': 'https://avatars.githubusercontent.com/u/49213714?v=4',
    'email': 'mohamedshawadfi@gmail.com',
    'phone': 0540814455,
    'job_title': 'Labours',
    'address': 'Faysaliah - Jeddah - Saudi Arabia',
    'department': 'Labours',
    'nationality': 'Egyptian',
    'id_number': '2506763016',
    'six': 'male',
    'date_of_birth': '23/02/1998',
    'education': 'Engineering',
    'status': 'Married',
    'contract_about': 'أي كلام في اي بتنجان اهو كله ع الفاضي ياغالي المهم انت تعمل اللي عليك واحنا نعمل اللي علينا الباقي شكليات ياوحش الكون :)',
    'contract_start': '1/11/2023',
    'contract_end': '31/10/2024',
    'basic_salary': '5000',
    'transportation': '500',
    'housing': '1000',
    'substance': '0',
    'insurance': '0',
    'gov_fees': '3000',
    'days_per_weak': '5',
    'start_day_of_weak': 'Sunday',
    'end_day_of_weak': 'Thursday',
    'hours_per_day': '8',
    'attendance': 'From 8 AM to 4 PM',
    'total_hours': '210',
    'overtime': '20',
    'deduction': '6',
    'bonus': '0',
  },
];